#+TITLE: Portfolio TODO
#+AUTHOR: Matei Cloteaux

A list of things I want to do with my portfolio site.
The site will be similar esque to zen garden where I
will have multiple presentations of the same content.
The html will not necessarily be shared, but the words
will be spread around the site.

* DONE Write site content
CLOSED: [2025-06-15 Sun 23:29]
- State "DONE"       from "TODO"       [2025-06-15 Sun 23:29]
Site content can be written down in one or multiple
json files. Each iteration of pages will grab that
content and display it however it chooses

* IN-PROGRESS Switching between site page styles

- State "IN-PROGRESS" from "TODO"       [2025-08-20 Wed 12:03] \\
  So theres a homepage where you can select which page you
  want to go to. I dont know if specific pages should have
  a link bringing you back to the homepage. Maybe just rely
  on users using browser back arrows?

  Leaving as in progress for now...
  
* Site page ideas:
Some ideas for the site pages

** DONE Plain HTML
CLOSED: [2025-06-15 Sun 23:29]
- State "DONE"       from "IN-PROGRESS" [2025-06-15 Sun 23:29]
- State "IN-PROGRESS" from "TODO"       [2025-06-15 Sun 19:43] \\
  Mostly finished. Just adding last touches
Just a plain html minimal css display. For funsies

** TODO Legit portfolio
Maybe a legit portfolio page that's actually
professional. Something to show off idk.

** TODO Old computer
An old timey computer were each page is a desktop
app and you open them in small windows. Could be
based off of Windows XP or Windows 95.

** DONE Ugly as hell
CLOSED: [2025-08-20 Wed 12:02]
- State "DONE"       from "IN-PROGRESS" [2025-08-20 Wed 12:02]
- State "IN-PROGRESS" from "TODO"       [2025-06-15 Sun 23:29] \\
  Just starting. Mostly scared to do legit ones...
Just a really ugly site. Terrible corlors. The
background is a repeated picture of my face.

*** DONE Moving images
CLOSED: [2025-08-20 Wed 12:02]
- State "DONE"       from "TODO"       [2025-08-20 Wed 12:02]
Images that appear and bounce arounf the screen.
They disappear when you click on them, but if you
misclick, more appear.

** TODO Full terminal
Terminal where you have to type commands to view
the content

* Page links that should be there:
List of pages that should be easily accessible on the
site. Some of these could be merged into one single page
as well. Like about and projects could all be on one page

** About page
General about me. Could include a picture of me

** Resume
My resume (as html or easy printable pdf)

** Projects
List of projects I want to show off. Includes:
- title
- link
- description
- technologies
- image?
  
** Education
Show current education. Potentially show transcript?

** Random stuff?
- Advent of code stats
- Spotify stats
- GD stats
- GH stats
  

